[package]
name = "bool_num"
version = "0.1.0"
authors = ["Alexander Bagnall <ab667712@ohio.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
